<?php

namespace Database\Seeders;

use App\Models\ContentBlock;
use Illuminate\Database\Seeder;

class DefaultContentSeeder extends Seeder
{
    /**
     * Seed all content blocks for all 4 languages from i18n data.
     * Keys match the i18n.js dictionary exactly so the frontend template can
     * use the same identifiers.
     */
    public function run(): void
    {
        $langs = ['ar', 'en', 'nl', 'de'];

        foreach ($langs as $lang) {
            $t = $this->translations($lang);

            // -----------------------------------------------------------------
            // nav
            // -----------------------------------------------------------------
            $this->seed('nav', $lang, [
                'home'     => $t['nav.home'],
                'features' => $t['nav.features'],
                'pricing'  => $t['nav.pricing'],
                'faq'      => $t['nav.faq'],
                'contact'  => $t['nav.contact'],
                'login'    => $t['nav.login'],
                'cta'      => $t['nav.cta'],
            ]);

            // -----------------------------------------------------------------
            // hero  (hero.* + ds.* + sec.*)
            // -----------------------------------------------------------------
            $this->seedWith('hero', $lang, [
                'title' => [$t['hero.title'], 'html'],
                'sub'   => [$t['hero.sub'],   'text'],
                'cta1'  => [$t['hero.cta1'],  'text'],
                'cta2'  => [$t['hero.cta2'],  'text'],
            ]);
            $this->seed('hero', $lang, [
                'ds.dashboard'    => $t['ds.dashboard'],
                'ds.manage'       => $t['ds.manage'],
                'ds.projects'     => $t['ds.projects'],
                'ds.tasks'        => $t['ds.tasks'],
                'ds.clients'      => $t['ds.clients'],
                'ds.invoices'     => $t['ds.invoices'],
                'ds.payments'     => $t['ds.payments'],
                'ds.general'      => $t['ds.general'],
                'ds.staff'        => $t['ds.staff'],
                'ds.attendance'   => $t['ds.attendance'],
                'ds.reports'      => $t['ds.reports'],
                'ds.settings'     => $t['ds.settings'],
                'ds.tabToday'     => $t['ds.tabToday'],
                'ds.tabRes'       => $t['ds.tabRes'],
                'ds.tabInv'       => $t['ds.tabInv'],
                'ds.search'       => $t['ds.search'],
                'ds.totalOrders'  => $t['ds.totalOrders'],
                'ds.avgInv'       => $t['ds.avgInv'],
                'ds.weeklySales'  => $t['ds.weeklySales'],
                'ds.sales'        => $t['ds.sales'],
                'ds.delta1'       => $t['ds.delta1'],
                'ds.delta2'       => $t['ds.delta2'],
                'ds.todayOrders'  => $t['ds.todayOrders'],
                'ds.paid'         => $t['ds.paid'],
                'ds.preparing'    => $t['ds.preparing'],
                'ds.order103'     => $t['ds.order103'],
                'ds.order102'     => $t['ds.order102'],
                'ds.order101'     => $t['ds.order101'],
                'ds.order100'     => $t['ds.order100'],
                'ds.order099'     => $t['ds.order099'],
                'sec.controlTitle'  => $t['sec.controlTitle'],
                'sec.controlLead'   => $t['sec.controlLead'],
                'sec.allInOneTitle' => $t['sec.allInOneTitle'],
                'sec.allInOneLead'  => $t['sec.allInOneLead'],
                'sec.testTitle'     => $t['sec.testTitle'],
                'sec.testLead'      => $t['sec.testLead'],
                'sec.pricingTitle'  => $t['sec.pricingTitle'],
                'sec.pricingLead'   => $t['sec.pricingLead'],
                'sec.faqTitle'      => $t['sec.faqTitle'],
                'sec.faqLead'       => $t['sec.faqLead'],
                'sec.contactTitle'  => $t['sec.contactTitle'],
                'sec.contactLead'   => $t['sec.contactLead'],
            ]);

            // -----------------------------------------------------------------
            // spotlight1  (sp.orders.* + mock.*)
            // -----------------------------------------------------------------
            $this->seed('spotlight1', $lang, [
                'sp.orders.h'    => $t['sp.orders.h'],
                'sp.orders.p'    => $t['sp.orders.p'],
                'sp.orders.l1'   => $t['sp.orders.l1'],
                'sp.orders.l2'   => $t['sp.orders.l2'],
                'sp.orders.l3'   => $t['sp.orders.l3'],
                'mock.customer1' => $t['mock.customer1'],
                'mock.date1'     => $t['mock.date1'],
                'mock.paid'      => $t['mock.paid'],
                'mock.item'      => $t['mock.item'],
                'mock.qty'       => $t['mock.qty'],
                'mock.price'     => $t['mock.price'],
                'mock.sum'       => $t['mock.sum'],
                'mock.burger'    => $t['mock.burger'],
                'mock.juice'     => $t['mock.juice'],
                'mock.salad'     => $t['mock.salad'],
                'mock.n1'        => $t['mock.n1'],
                'mock.n2'        => $t['mock.n2'],
                'mock.total'     => $t['mock.total'],
                'mock.totalVal'  => $t['mock.totalVal'],
                'mock.order047'  => $t['mock.order047'],
                'mock.cust2'     => $t['mock.cust2'],
                'mock.new'       => $t['mock.new'],
                'mock.amount'    => $t['mock.amount'],
                'mock.payOk'     => $t['mock.payOk'],
            ]);

            // -----------------------------------------------------------------
            // spotlight2  (sp.res.* + res.*)
            // -----------------------------------------------------------------
            $this->seed('spotlight2', $lang, [
                'sp.res.h'      => $t['sp.res.h'],
                'sp.res.p'      => $t['sp.res.p'],
                'sp.res.l1'     => $t['sp.res.l1'],
                'sp.res.l2'     => $t['sp.res.l2'],
                'sp.res.l3'     => $t['sp.res.l3'],
                'res.title'     => $t['res.title'],
                'res.from'      => $t['res.from'],
                'res.to'        => $t['res.to'],
                'res.dateA'     => $t['res.dateA'],
                'res.dateB'     => $t['res.dateB'],
                'res.t4'        => $t['res.t4'],
                'res.fam'       => $t['res.fam'],
                'res.confirmed' => $t['res.confirmed'],
                'res.t7'        => $t['res.t7'],
                'res.phone'     => $t['res.phone'],
                'res.pending'   => $t['res.pending'],
                'res.t2'        => $t['res.t2'],
                'res.cust3'     => $t['res.cust3'],
                'res.arrived'   => $t['res.arrived'],
                'res.t9'        => $t['res.t9'],
                'res.cust4'     => $t['res.cust4'],
            ]);

            // -----------------------------------------------------------------
            // spotlight3  (sp.menu.* + menu.*)
            // -----------------------------------------------------------------
            $this->seed('spotlight3', $lang, [
                'sp.menu.h'   => $t['sp.menu.h'],
                'sp.menu.p'   => $t['sp.menu.p'],
                'sp.menu.l1'  => $t['sp.menu.l1'],
                'sp.menu.l2'  => $t['sp.menu.l2'],
                'sp.menu.l3'  => $t['sp.menu.l3'],
                'menu.tab1'   => $t['menu.tab1'],
                'menu.tab2'   => $t['menu.tab2'],
                'menu.tab3'   => $t['menu.tab3'],
                'menu.update' => $t['menu.update'],
                'menu.i1n'    => $t['menu.i1n'],
                'menu.i1d'    => $t['menu.i1d'],
                'menu.p42'    => $t['menu.p42'],
                'menu.i2n'    => $t['menu.i2n'],
                'menu.i2d'    => $t['menu.i2d'],
                'menu.p38'    => $t['menu.p38'],
                'menu.i3n'    => $t['menu.i3n'],
                'menu.i3d'    => $t['menu.i3d'],
                'menu.p28'    => $t['menu.p28'],
                'menu.i4n'    => $t['menu.i4n'],
                'menu.i4d'    => $t['menu.i4d'],
                'menu.p45'    => $t['menu.p45'],
            ]);

            // -----------------------------------------------------------------
            // features  (ft.*)
            // -----------------------------------------------------------------
            $this->seed('features', $lang, [
                'ft.pos.h'   => $t['ft.pos.h'],
                'ft.pos.p'   => $t['ft.pos.p'],
                'ft.rep.h'   => $t['ft.rep.h'],
                'ft.rep.p'   => $t['ft.rep.p'],
                'ft.inv.h'   => $t['ft.inv.h'],
                'ft.inv.p'   => $t['ft.inv.p'],
                'ft.stock.h' => $t['ft.stock.h'],
                'ft.stock.p' => $t['ft.stock.p'],
                'ft.staff.h' => $t['ft.staff.h'],
                'ft.staff.p' => $t['ft.staff.p'],
                'ft.comm.h'  => $t['ft.comm.h'],
                'ft.comm.p'  => $t['ft.comm.p'],
                'ft.pay.h'   => $t['ft.pay.h'],
                'ft.pay.p'   => $t['ft.pay.p'],
                'ft.sup.h'   => $t['ft.sup.h'],
                'ft.sup.p'   => $t['ft.sup.p'],
            ]);

            // -----------------------------------------------------------------
            // testimonials  (q1.* q2.* q3.*)
            // -----------------------------------------------------------------
            $this->seed('testimonials', $lang, [
                'q1.body' => $t['q1.body'],
                'q1.name' => $t['q1.name'],
                'q1.role' => $t['q1.role'],
                'q2.body' => $t['q2.body'],
                'q2.name' => $t['q2.name'],
                'q2.role' => $t['q2.role'],
                'q3.body' => $t['q3.body'],
                'q3.name' => $t['q3.name'],
                'q3.role' => $t['q3.role'],
            ]);

            // -----------------------------------------------------------------
            // pricing  (pr.* + pt.*)
            // -----------------------------------------------------------------
            $this->seed('pricing', $lang, [
                'pr.monthly'              => $t['pr.monthly'],
                'pr.yearly'               => $t['pr.yearly'],
                'pr.basic'                => $t['pr.basic'],
                'pr.pro'                  => $t['pr.pro'],
                'pr.per'                  => $t['pr.per'],
                'pr.basicNote'            => $t['pr.basicNote'],
                'pr.proNote'              => $t['pr.proNote'],
                'pr.start'                => $t['pr.start'],
                'pr.popular'              => $t['pr.popular'],
                'pr.price.basic.monthly'  => $t['pr.price.basic.monthly'],
                'pr.price.basic.yearly'   => $t['pr.price.basic.yearly'],
                'pr.price.pro.monthly'    => $t['pr.price.pro.monthly'],
                'pr.price.pro.yearly'     => $t['pr.price.pro.yearly'],
                'pt.features'             => $t['pt.features'],
                'pt.branches'             => $t['pt.branches'],
                'pt.one'                  => $t['pt.one'],
                'pt.unlim'                => $t['pt.unlim'],
                'pt.staffN'               => $t['pt.staffN'],
                'pt.upto5'                => $t['pt.upto5'],
                'pt.posR'                 => $t['pt.posR'],
                'pt.ordRes'               => $t['pt.ordRes'],
                'pt.invR'                 => $t['pt.invR'],
                'pt.advRep'               => $t['pt.advRep'],
                'pt.deliv'                => $t['pt.deliv'],
                'pt.supp'                 => $t['pt.supp'],
                'pt.email'                => $t['pt.email'],
                'pt.support247'           => $t['pt.support247'],
            ]);

            // -----------------------------------------------------------------
            // faq  (faq.*)
            // -----------------------------------------------------------------
            $this->seed('faq', $lang, [
                'faq.q1' => $t['faq.q1'],
                'faq.a1' => $t['faq.a1'],
                'faq.q2' => $t['faq.q2'],
                'faq.a2' => $t['faq.a2'],
                'faq.q3' => $t['faq.q3'],
                'faq.a3' => $t['faq.a3'],
                'faq.q4' => $t['faq.q4'],
                'faq.a4' => $t['faq.a4'],
                'faq.q5' => $t['faq.q5'],
                'faq.a5' => $t['faq.a5'],
                'faq.q6' => $t['faq.q6'],
                'faq.a6' => $t['faq.a6'],
            ]);

            // -----------------------------------------------------------------
            // contact  (ct.*)
            // -----------------------------------------------------------------
            $this->seed('contact', $lang, [
                'ct.loc'      => $t['ct.loc'],
                'ct.locV'     => $t['ct.locV'],
                'ct.locL'     => $t['ct.locL'],
                'ct.email'    => $t['ct.email'],
                'ct.emailL'   => $t['ct.emailL'],
                'ct.phone'    => $t['ct.phone'],
                'ct.phoneL'   => $t['ct.phoneL'],
                'ct.book'     => $t['ct.book'],
                'ct.imgTitle' => $t['ct.imgTitle'],
                'ct.imgSub'   => $t['ct.imgSub'],
            ]);

            // -----------------------------------------------------------------
            // footer  (footer.*)
            // -----------------------------------------------------------------
            $this->seed('footer', $lang, [
                'footer.rights' => $t['footer.rights'],
            ]);

            // -----------------------------------------------------------------
            // seo  — page <title> per language
            // -----------------------------------------------------------------
            ContentBlock::upsert('seo', 'title', $lang, $t['title'], 'text');
        }
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    /** Upsert an array of key => value pairs for a section/lang, all type=text. */
    private function seed(string $section, string $lang, array $pairs): void
    {
        foreach ($pairs as $key => $value) {
            ContentBlock::upsert($section, $key, $lang, (string) $value, 'text');
        }
    }

    /**
     * Upsert an array of key => [value, type] pairs for a section/lang.
     * Used when some keys need a non-default type (e.g. html).
     */
    private function seedWith(string $section, string $lang, array $pairs): void
    {
        foreach ($pairs as $key => [$value, $type]) {
            ContentBlock::upsert($section, $key, $lang, (string) $value, $type);
        }
    }

    // -------------------------------------------------------------------------
    // Translation data (sourced from public/i18n.js)
    // -------------------------------------------------------------------------

    private function translations(string $lang): array
    {
        return match ($lang) {
            'ar' => $this->ar(),
            'en' => $this->en(),
            'nl' => $this->nl(),
            'de' => $this->de(),
            default => [],
        };
    }

    private function ar(): array
    {
        return [
            'title' => 'Retont Business — أدر مشاريعك وفريقك من مكان واحد',

            'nav.home'     => 'الرئيسية',
            'nav.features' => 'المميزات',
            'nav.pricing'  => 'الأسعار',
            'nav.faq'      => 'الأسئلة الشائعة',
            'nav.contact'  => 'تواصل معنا',
            'nav.login'    => 'تسجيل الدخول',
            'nav.cta'      => 'ابدأ الآن',

            'hero.title' => 'منصة <span class="accent">Retont Business</span><br/>لإدارة مشاريعك وفريقك بسلاسة',
            'hero.sub'   => 'أدر المشاريع والمهام والعملاء والفواتير من لوحة واحدة. تابع تقدّم العمل، سجّل ساعات الفريق، وأصدر فواتير دقيقة — بدون فوضى الأدوات المتفرّقة.',
            'hero.cta1'  => 'ابدأ تجربة ٣٠ يومًا مجانًا',
            'hero.cta2'  => 'شاهد العرض التوضيحي',

            'ds.dashboard'    => 'لوحة التحكم',
            'ds.manage'       => 'إدارة العمل',
            'ds.projects'     => 'المشاريع',
            'ds.tasks'        => 'المهام',
            'ds.clients'      => 'العملاء',
            'ds.invoices'     => 'الفواتير',
            'ds.payments'     => 'المدفوعات',
            'ds.general'      => 'عام',
            'ds.staff'        => 'الموظفون',
            'ds.attendance'   => 'الحضور والانصراف',
            'ds.reports'      => 'التقارير',
            'ds.settings'     => 'الإعدادات',
            'ds.tabToday'     => 'مهام اليوم',
            'ds.tabRes'       => 'مشاريع نشطة',
            'ds.tabInv'       => 'ساعات العمل',
            'ds.search'       => '🔍 بحث سريع…',
            'ds.totalOrders'  => 'المشاريع النشطة',
            'ds.avgInv'       => 'المهام المنجزة',
            'ds.weeklySales'  => 'الإيرادات الأسبوعية',
            'ds.sales'        => '٤٢٬٧٥٠ ر.س',
            'ds.delta1'       => '▲ ٣ مشاريع جديدة هذا الأسبوع',
            'ds.delta2'       => '▲ ١٢٪ عن الشهر الماضي',
            'ds.todayOrders'  => 'مهام اليوم',
            'ds.paid'         => 'مكتمل',
            'ds.preparing'    => 'قيد التنفيذ',
            'ds.order103'     => 'مشروع موقع شركة سواحل',
            'ds.order102'     => 'مشروع تطبيق نقل',
            'ds.order101'     => 'متجر بسمة الإلكتروني',
            'ds.order100'     => 'فريق التطوير الداخلي',
            'ds.order099'     => 'مؤسسة الأفق التجارية',

            'sec.controlTitle'  => 'تحكّم في إدارة <span class="accent">أعمالك</span>',
            'sec.controlLead'   => 'ثلاث وحدات أساسية في منصة واحدة لإدارة عملك اليومي — المشاريع والمهام وإدارة العملاء.',
            'sec.allInOneTitle' => 'كل ما تحتاجه <span class="accent">في مكان واحد</span>',
            'sec.allInOneLead'  => 'منظومة متكاملة لإدارة كل جوانب عملك — من المشاريع إلى الموظفين إلى تقارير الأداء.',
            'sec.testTitle'     => 'ماذا يقول <span class="accent">عملاؤنا</span>',
            'sec.testLead'      => 'آلاف الفرق والشركات تعتمد على Retont Business لتشغيل أعمالها اليومية.',
            'sec.pricingTitle'  => 'خطط واضحة <span class="accent">ومرنة</span>',
            'sec.pricingLead'   => 'اختر الخطة المناسبة لحجم فريقك. بدون رسوم مخفية، يمكنك إلغاء الاشتراك في أي وقت.',
            'sec.faqTitle'      => 'الأسئلة <span class="accent">الشائعة</span>',
            'sec.faqLead'       => 'إجابات على أكثر الأسئلة شيوعًا حول منصة Retont Business.',
            'sec.contactTitle'  => 'تواصل <span class="accent">معنا</span>',
            'sec.contactLead'   => 'فريقنا جاهز للإجابة على استفساراتك وتقديم عرض توضيحي مخصص لعملك.',

            'mock.customer1' => 'مؤسسة الأفق التجارية',
            'mock.date1'     => 'فاتورة #INV‑2026‑047 · ١٥ مايو ٢٠٢٦',
            'mock.paid'      => 'مدفوعة',
            'mock.item'      => 'البند',
            'mock.qty'       => 'الساعات',
            'mock.price'     => 'السعر/س',
            'mock.sum'       => 'المجموع',
            'mock.burger'    => 'تصميم واجهات المستخدم',
            'mock.juice'     => 'تطوير الواجهة الأمامية',
            'mock.salad'     => 'إدارة المشروع والمتابعة',
            'mock.n1'        => '٢٤',
            'mock.n2'        => '٣٢',
            'mock.total'     => 'الإجمالي (شامل الضريبة)',
            'mock.totalVal'  => '١٢٬١٧٢ ر.س',
            'mock.order047'  => 'مشروع #٠٤٧',
            'mock.cust2'     => 'شركة نسائم للتقنية',
            'mock.new'       => 'قيد التنفيذ',
            'mock.amount'    => '٧٬٤٥٠ ر.س',
            'mock.payOk'     => 'دفعة جديدة مستلمة',

            'sp.orders.h'  => 'من المهمة إلى الفاتورة دون جهد',
            'sp.orders.p'  => 'حوّل ساعات العمل المسجّلة إلى فواتير دقيقة بضغطة زر. تابع الدفعات، أرسل التذكيرات تلقائيًا، واحتفظ بسجلّ مالي كامل لكل عميل ومشروع.',
            'sp.orders.l1' => 'فواتير احترافية بعملات متعدّدة مع توافق ضريبي كامل',
            'sp.orders.l2' => 'تذكيرات دفع آلية عبر البريد الإلكتروني والرسائل الفورية',
            'sp.orders.l3' => 'ربط مباشر بأنظمة الدفع الإلكترونية الرائدة',

            'sp.res.h'  => 'لوحة بصرية لإدارة المهام',
            'sp.res.p'  => 'نظّم مهام الفريق بطريقة بصرية مرنة: من المسودّة إلى الإنجاز. اسحب وأفلت، وزّع المسؤوليات، وراقب الاختناقات قبل أن تتأخر المشاريع.',
            'sp.res.l1' => 'عروض متعددة — البطاقات والمخطط الزمني والقائمة — بنفس البيانات',
            'sp.res.l2' => 'إسناد المهام مع مواعيد نهائية وأولويات',
            'sp.res.l3' => 'تتبّع ساعات العمل لكل مهمة وموظف',

            'sp.menu.h'  => 'نظام متكامل لإدارة علاقات العملاء',
            'sp.menu.p'  => 'احفظ جهات الاتصال، تتبّع الفرص البيعية من العرض حتى الإغلاق، ووثّق كل تفاعل مع العميل في صفحته. حوّل المحادثات إلى مشاريع، وانقل العروض إلى عقود بضغطة زر.',
            'sp.menu.l1' => 'مسار مبيعات قابل للتخصيص',
            'sp.menu.l2' => 'سجل كامل للعروض والعقود لكل عميل',
            'sp.menu.l3' => 'بوابة عملاء آمنة لمشاركة المشاريع والفواتير',

            'res.title'     => 'لوحة المشاريع',
            'res.from'      => 'الفترة',
            'res.to'        => 'المشروع',
            'res.dateA'     => '١٥ – ٢٢ مايو',
            'res.dateB'     => 'موقع سواحل',
            'res.t4'        => 'تصميم الصفحة الرئيسية',
            'res.fam'       => 'سارة المطيري · أولوية عالية',
            'res.confirmed' => 'مكتملة',
            'res.t7'        => 'برمجة واجهة المستخدم',
            'res.phone'     => 'يستحقّ ٢٠ مايو · ١٢ ساعة',
            'res.pending'   => 'قيد التنفيذ',
            'res.t2'        => 'إعداد قاعدة البيانات',
            'res.cust3'     => 'فيصل النمر · أولوية متوسطة',
            'res.arrived'   => 'قيد المراجعة',
            'res.t9'        => 'اختبار الجودة',
            'res.cust4'     => 'نورة الزهراني · ٤ مهام فرعية',

            'menu.tab1'   => 'عملاء نشطون',
            'menu.tab2'   => 'عملاء محتملون',
            'menu.tab3'   => 'مؤرشف',
            'menu.update' => 'إضافة عميل',
            'menu.i1n'    => 'مؤسسة الأفق التجارية',
            'menu.i1d'    => '٣ مشاريع نشطة · آخر تواصل قبل يومين',
            'menu.p42'    => '٤٢٬٠٠٠ ر.س',
            'menu.i2n'    => 'شركة نسائم للتقنية',
            'menu.i2d'    => 'مشروعان نشطان · فاتورة معلّقة',
            'menu.p38'    => '٣٨٬٥٠٠ ر.س',
            'menu.i3n'    => 'متجر بسمة الإلكتروني',
            'menu.i3d'    => 'مشروع واحد · في مرحلة الاختبار',
            'menu.p28'    => '٢٨٬٢٠٠ ر.س',
            'menu.i4n'    => 'مجموعة وجهة الرياض',
            'menu.i4d'    => '٤ مشاريع · عميل مميز منذ ٢٠٢٣',
            'menu.p45'    => '٤٥٬٩٠٠ ر.س',

            'ft.pos.h'   => 'إدارة المشاريع',
            'ft.pos.p'   => 'خطّط ونفّذ وراقب مشاريعك بعروض البطاقات والمخطط الزمني والقائمة.',
            'ft.rep.h'   => 'تقارير ذكية',
            'ft.rep.p'   => 'تقارير حيّة وفورية عن الإيرادات والإنتاجية والربحية لكل مشروع.',
            'ft.inv.h'   => 'الفواتير والعروض',
            'ft.inv.p'   => 'عروض أسعار وفواتير وعقود إلكترونية بتوافق ضريبي كامل.',
            'ft.stock.h' => 'تتبّع ساعات العمل',
            'ft.stock.p' => 'سجّل ساعات الفريق على كل مهمة، واحسب التكلفة والربحية تلقائيًا.',
            'ft.staff.h' => 'الموارد البشرية والصلاحيات',
            'ft.staff.p' => 'إدارة الفريق والإجازات والحضور والانصراف وصلاحيات كل دور وظيفي.',
            'ft.comm.h'  => 'دردشة الفريق',
            'ft.comm.p'  => 'قنوات نقاش لكل مشروع وإشعارات فورية وتعليقات على المهام.',
            'ft.pay.h'   => 'المدفوعات الإلكترونية',
            'ft.pay.p'   => 'قبول البطاقات الائتمانية ومدى والتحويلات البنكية وعدد من بوابات الدفع الرائدة.',
            'ft.sup.h'   => 'تذاكر الدعم الفني',
            'ft.sup.p'   => 'نظام دعم فني مدمج لاستقبال طلبات العملاء والردّ عليها بسرعة.',

            'q1.body' => '"كنّا نستخدم خمسة أدوات مختلفة لإدارة المشاريع والفواتير. اليوم كل شيء داخل Retont Business — وفّرنا أكثر من ٢٠٪ من وقت الإدارة شهريًا."',
            'q1.name' => 'خالد العمري',
            'q1.role' => 'المدير التنفيذي · وكالة إثراء الرقمية',
            'q2.body' => '"تتبّع ساعات العمل والربط بين المهام والفواتير غيّر طريقة عملنا. أصبحنا نعرف ربحية كل مشروع بدقة وفي الوقت الفعلي."',
            'q2.name' => 'ريم الدوسري',
            'q2.role' => 'مديرة العمليات · استوديو نَمَط',
            'q3.body' => '"بوابة العملاء أعطت شركتنا مظهرًا احترافيًا حقيقيًا. عملاؤنا يدخلون يطّلعون على تقدّم المشروع ويدفعون الفواتير بسهولة."',
            'q3.name' => 'ماجد الشهري',
            'q3.role' => 'شريك مؤسس · شركة تطوير برمجيات',

            'pr.monthly'              => 'شهري',
            'pr.yearly'               => 'سنوي · وفّر ٢٠٪',
            'pr.basic'                => 'الباقة الأساسية',
            'pr.pro'                  => 'الباقة الاحترافية',
            'pr.per'                  => 'ر.س/شهر',
            'pr.basicNote'            => 'للفرق الصغيرة حتى ٥ مستخدمين',
            'pr.proNote'              => 'للشركات المتنامية بمستخدمين غير محدودين',
            'pr.start'                => 'ابدأ تجربتك',
            'pr.popular'              => 'الأكثر شعبية',
            'pr.price.basic.monthly'  => '199',
            'pr.price.basic.yearly'   => '159',
            'pr.price.pro.monthly'    => '499',
            'pr.price.pro.yearly'     => '399',

            'pt.features'   => 'المميزات',
            'pt.branches'   => 'عدد المشاريع',
            'pt.one'        => 'حتى ١٠ مشاريع',
            'pt.unlim'      => 'غير محدود',
            'pt.staffN'     => 'عدد المستخدمين',
            'pt.upto5'      => 'حتى ٥',
            'pt.posR'       => 'إدارة المشاريع والمهام',
            'pt.ordRes'     => 'الفواتير والعروض',
            'pt.invR'       => 'إدارة العملاء وبوابتهم',
            'pt.advRep'     => 'تقارير وتحليلات متقدمة',
            'pt.deliv'      => 'تكامل مع المدفوعات الإلكترونية',
            'pt.supp'       => 'الدعم الفني',
            'pt.email'      => 'بريد إلكتروني',
            'pt.support247' => 'دعم مخصص ٢٤/٧',

            'faq.q1' => 'هل أستطيع تجربة المنصة قبل الاشتراك؟',
            'faq.a1' => 'نعم، نقدّم تجربة مجانية لمدة ٣٠ يومًا بكل المميزات دون الحاجة لبطاقة ائتمانية.',
            'faq.q2' => 'هل المنصة سحابية أم تعمل على خوادمي؟',
            'faq.a2' => 'المنصة سحابية بالكامل — لا حاجة لتثبيت أو صيانة. تعمل من أي متصفّح أو جهاز.',
            'faq.q3' => 'هل تدعم المنصة الفوترة الإلكترونية؟',
            'faq.a3' => 'نعم، نحن متوافقون بالكامل مع متطلبات هيئة الزكاة والضريبة والجمارك للفوترة الإلكترونية في السعودية.',
            'faq.q4' => 'هل يمكنني نقل بياناتي من نظام آخر؟',
            'faq.a4' => 'بالتأكيد، فريقنا التقني يساعدك في نقل بيانات العملاء والمشاريع والفواتير مجانًا من أي نظام سابق.',
            'faq.q5' => 'ما طرق الدفع المقبولة من عملائي؟',
            'faq.a5' => 'يمكن لعملائك الدفع عبر البطاقات الائتمانية ومدى وعدد من بوابات الدفع الإلكترونية والتحويل البنكي.',
            'faq.q6' => 'هل أستطيع إلغاء الاشتراك في أي وقت؟',
            'faq.a6' => 'نعم، الاشتراك شهري ويمكنك إلغاؤه في أي وقت دون رسوم إضافية.',

            'ct.loc'      => 'الموقع',
            'ct.locV'     => 'الرياض، المملكة العربية السعودية',
            'ct.locL'     => 'طريق الملك فهد، حي العليا',
            'ct.email'    => 'البريد الإلكتروني',
            'ct.emailL'   => 'للاستفسارات العامة والمبيعات',
            'ct.phone'    => 'الهاتف',
            'ct.phoneL'   => 'من الأحد إلى الخميس · ٩ صباحًا – ٦ مساءً',
            'ct.book'     => 'احجز عرضًا توضيحيًا',
            'ct.imgTitle' => 'نحن هنا لمساعدتك',
            'ct.imgSub'   => 'تواصل معنا في أي وقت — فريق Retont Business جاهز لخدمتك.',

            'footer.rights' => '© ٢٠٢٦ Retont Business. جميع الحقوق محفوظة.',
        ];
    }

    private function en(): array
    {
        return [
            'title' => 'Retont Business — Run your projects and team in one place',

            'nav.home'     => 'Home',
            'nav.features' => 'Features',
            'nav.pricing'  => 'Pricing',
            'nav.faq'      => 'FAQ',
            'nav.contact'  => 'Contact',
            'nav.login'    => 'Login',
            'nav.cta'      => 'Get Started',

            'hero.title' => '<span class="accent">Retont Business</span> —<br/>Run your projects and team in one place',
            'hero.sub'   => 'Manage projects, tasks, clients and invoices from a single dashboard. Track progress, log team hours, and issue accurate invoices — without the chaos of scattered tools.',
            'hero.cta1'  => 'Start 30‑day free trial',
            'hero.cta2'  => 'Watch the demo',

            'ds.dashboard'    => 'Dashboard',
            'ds.manage'       => 'Work',
            'ds.projects'     => 'Projects',
            'ds.tasks'        => 'Tasks',
            'ds.clients'      => 'Clients',
            'ds.invoices'     => 'Invoices',
            'ds.payments'     => 'Payments',
            'ds.general'      => 'General',
            'ds.staff'        => 'Team',
            'ds.attendance'   => 'Attendance',
            'ds.reports'      => 'Reports',
            'ds.settings'     => 'Settings',
            'ds.tabToday'     => "Today's Tasks",
            'ds.tabRes'       => 'Active Projects',
            'ds.tabInv'       => 'Time Logs',
            'ds.search'       => '🔍 Quick search…',
            'ds.totalOrders'  => 'Active Projects',
            'ds.avgInv'       => 'Tasks Completed',
            'ds.weeklySales'  => 'Weekly Revenue',
            'ds.sales'        => '$11,400',
            'ds.delta1'       => '▲ 3 new projects this week',
            'ds.delta2'       => '▲ 12% vs last month',
            'ds.todayOrders'  => "Today's Tasks",
            'ds.paid'         => 'Done',
            'ds.preparing'    => 'In Progress',
            'ds.order103'     => 'Sawahel Co. Website',
            'ds.order102'     => 'Transport App Project',
            'ds.order101'     => 'Basma E‑Store',
            'ds.order100'     => 'Internal Dev Team',
            'ds.order099'     => 'Al‑Ofuq Trading Co.',

            'sec.controlTitle'  => 'Take control of <span class="accent">your business</span>',
            'sec.controlLead'   => 'Three core modules in one platform to run your day‑to‑day — Projects, Tasks and Clients.',
            'sec.allInOneTitle' => 'Everything you need <span class="accent">in one place</span>',
            'sec.allInOneLead'  => 'A complete platform for every side of your business — from projects to people to performance reports.',
            'sec.testTitle'     => 'What our <span class="accent">customers say</span>',
            'sec.testLead'      => 'Thousands of teams and businesses trust Retont Business to run their daily operations.',
            'sec.pricingTitle'  => 'Simple, <span class="accent">transparent pricing</span>',
            'sec.pricingLead'   => 'Pick the plan that fits your team. No hidden fees — cancel anytime.',
            'sec.faqTitle'      => 'Frequently asked <span class="accent">questions</span>',
            'sec.faqLead'       => 'Answers to the most common questions about the Retont Business platform.',
            'sec.contactTitle'  => 'Get in <span class="accent">touch</span>',
            'sec.contactLead'   => 'Our team is ready to answer your questions and prepare a custom demo for your business.',

            'mock.customer1' => 'Al‑Ofuq Trading Co.',
            'mock.date1'     => 'Invoice #INV‑2026‑047 · May 15, 2026',
            'mock.paid'      => 'Paid',
            'mock.item'      => 'Item',
            'mock.qty'       => 'Hours',
            'mock.price'     => 'Rate/hr',
            'mock.sum'       => 'Total',
            'mock.burger'    => 'UI/UX Design',
            'mock.juice'     => 'Frontend Development',
            'mock.salad'     => 'Project Management',
            'mock.n1'        => '24',
            'mock.n2'        => '32',
            'mock.total'     => 'Total (incl. VAT)',
            'mock.totalVal'  => '$3,245',
            'mock.order047'  => 'Project #047',
            'mock.cust2'     => 'Nasaem Tech Co.',
            'mock.new'       => 'In Progress',
            'mock.amount'    => '$1,985',
            'mock.payOk'     => 'New payment received',

            'sp.orders.h'  => 'From task to invoice, effortlessly',
            'sp.orders.p'  => 'Turn logged hours into accurate invoices in one click. Track payments, send automated reminders, and keep a full financial trail for every client and project.',
            'sp.orders.l1' => 'Professional multi‑currency invoices with tax compliance',
            'sp.orders.l2' => 'Automated payment reminders via email and WhatsApp',
            'sp.orders.l3' => 'Direct integration with Stripe, PayPal and local gateways',

            'sp.res.h'  => 'A visual board for task management',
            'sp.res.p'  => "Organize your team's work visually: from draft to done. Drag, drop, assign responsibilities, and spot bottlenecks before projects slip.",
            'sp.res.l1' => 'Kanban, Gantt and list views on the same data',
            'sp.res.l2' => 'Assign tasks with due dates and priorities',
            'sp.res.l3' => 'Time tracking per task and team member',

            'sp.menu.h'  => 'A built‑in CRM for client relationships',
            'sp.menu.p'  => "Store contacts, track sales opportunities from quote to close, and log every interaction on the client's page. Convert conversations into projects and quotes into contracts in one click.",
            'sp.menu.l1' => 'Customizable sales pipeline',
            'sp.menu.l2' => 'Full quote and contract history per client',
            'sp.menu.l3' => 'Secure client portal for projects and invoices',

            'res.title'     => 'Project Board',
            'res.from'      => 'Period',
            'res.to'        => 'Project',
            'res.dateA'     => 'May 15 – 22',
            'res.dateB'     => 'Sawahel Website',
            'res.t4'        => 'Homepage design',
            'res.fam'       => 'Sarah Al‑Mutairi · High priority',
            'res.confirmed' => 'Done',
            'res.t7'        => 'Frontend build',
            'res.phone'     => 'Due May 20 · 12 hours',
            'res.pending'   => 'In Progress',
            'res.t2'        => 'Database setup',
            'res.cust3'     => 'Faisal Al‑Nemer · Medium priority',
            'res.arrived'   => 'In Review',
            'res.t9'        => 'QA testing',
            'res.cust4'     => 'Noura Al‑Zahrani · 4 subtasks',

            'menu.tab1'   => 'Active Clients',
            'menu.tab2'   => 'Leads',
            'menu.tab3'   => 'Archived',
            'menu.update' => 'Add Client',
            'menu.i1n'    => 'Al‑Ofuq Trading Co.',
            'menu.i1d'    => '3 active projects · last contact 2 days ago',
            'menu.p42'    => '$11,200',
            'menu.i2n'    => 'Nasaem Tech Co.',
            'menu.i2d'    => '2 active projects · invoice pending',
            'menu.p38'    => '$10,260',
            'menu.i3n'    => 'Basma E‑Store',
            'menu.i3d'    => '1 project · in testing phase',
            'menu.p28'    => '$7,520',
            'menu.i4n'    => 'Riyadh Destination Group',
            'menu.i4d'    => '4 projects · VIP client since 2023',
            'menu.p45'    => '$12,240',

            'ft.pos.h'   => 'Project management',
            'ft.pos.p'   => 'Plan, execute and monitor projects with Kanban, Gantt and list views.',
            'ft.rep.h'   => 'Smart reports',
            'ft.rep.p'   => 'Live, instant reports on revenue, productivity and per‑project profitability.',
            'ft.inv.h'   => 'Invoices & estimates',
            'ft.inv.p'   => 'E‑quotes, e‑invoices and contracts with full tax compliance.',
            'ft.stock.h' => 'Time tracking',
            'ft.stock.p' => 'Log team hours per task; cost and profitability are calculated automatically.',
            'ft.staff.h' => 'Team & permissions',
            'ft.staff.p' => 'Manage team, leaves, attendance, and role‑based access.',
            'ft.comm.h'  => 'Team chat',
            'ft.comm.p'  => 'Project channels, instant notifications, and comments on tasks.',
            'ft.pay.h'   => 'Online payments',
            'ft.pay.p'   => 'Accept cards, Apple Pay, STC Pay, Stripe, PayPal and bank transfers.',
            'ft.sup.h'   => 'Support tickets',
            'ft.sup.p'   => 'Built‑in helpdesk to receive client requests and respond fast.',

            'q1.body' => '"We used to run five different tools for projects and billing. Today it all lives inside Retont Business — we save over 20% of monthly admin time."',
            'q1.name' => 'Khaled Al‑Omari',
            'q1.role' => 'CEO · Ithraa Digital Agency',
            'q2.body' => '"Linking time logs to tasks and invoices changed how we work. We now know each project\'s profitability accurately and in real time."',
            'q2.name' => 'Reem Al‑Dosari',
            'q2.role' => 'Operations Manager · Namat Studio',
            'q3.body' => '"The client portal made our company look genuinely professional. Clients log in, follow progress, and pay invoices easily."',
            'q3.name' => 'Majed Al‑Shehri',
            'q3.role' => 'Co‑Founder · Software Development Co.',

            'pr.monthly'              => 'Monthly',
            'pr.yearly'               => 'Yearly · save 20%',
            'pr.basic'                => 'Basic',
            'pr.pro'                  => 'Professional',
            'pr.per'                  => 'USD/month',
            'pr.basicNote'            => 'For small teams of up to 5 users',
            'pr.proNote'              => 'For growing companies with unlimited users',
            'pr.start'                => 'Start your trial',
            'pr.popular'              => 'Most popular',
            'pr.price.basic.monthly'  => '49',
            'pr.price.basic.yearly'   => '39',
            'pr.price.pro.monthly'    => '129',
            'pr.price.pro.yearly'     => '103',

            'pt.features'   => 'Features',
            'pt.branches'   => 'Projects',
            'pt.one'        => 'Up to 10 projects',
            'pt.unlim'      => 'Unlimited',
            'pt.staffN'     => 'Users',
            'pt.upto5'      => 'Up to 5',
            'pt.posR'       => 'Projects & tasks',
            'pt.ordRes'     => 'Invoices & estimates',
            'pt.invR'       => 'CRM & client portal',
            'pt.advRep'     => 'Advanced reports',
            'pt.deliv'      => 'Online payment integrations',
            'pt.supp'       => 'Support',
            'pt.email'      => 'Email',
            'pt.support247' => 'Dedicated 24/7',

            'faq.q1' => 'Can I try the platform before subscribing?',
            'faq.a1' => 'Yes — a 30‑day free trial with all features, no credit card required.',
            'faq.q2' => 'Is the platform cloud‑based or self‑hosted?',
            'faq.a2' => 'Fully cloud‑based (SaaS) — no installation, no maintenance. Works in any browser, on any device.',
            'faq.q3' => 'Do you support e‑invoicing?',
            'faq.a3' => "Yes, we're fully compliant with Saudi ZATCA e‑invoicing (Fatoora) requirements.",
            'faq.q4' => 'Can I migrate my data from another system?',
            'faq.a4' => 'Absolutely. Our team migrates your clients, projects and invoices for free from any prior system.',
            'faq.q5' => 'Which payment methods can my clients use?',
            'faq.a5' => 'Credit cards, mada, STC Pay, Apple Pay, Stripe, PayPal, and direct bank transfer.',
            'faq.q6' => 'Can I cancel anytime?',
            'faq.a6' => 'Yes — the subscription is monthly and can be cancelled anytime, no extra fees.',

            'ct.loc'      => 'Location',
            'ct.locV'     => 'Riyadh, Kingdom of Saudi Arabia',
            'ct.locL'     => 'King Fahd Road, Al‑Olaya',
            'ct.email'    => 'Email',
            'ct.emailL'   => 'For general inquiries and sales',
            'ct.phone'    => 'Phone',
            'ct.phoneL'   => 'Sunday – Thursday · 9 AM – 6 PM',
            'ct.book'     => 'Book a demo',
            'ct.imgTitle' => "We're here to help",
            'ct.imgSub'   => 'Reach out anytime — the Retont Business team is ready to serve you.',

            'footer.rights' => '© 2026 Retont Business. All rights reserved.',
        ];
    }

    private function nl(): array
    {
        return [
            'title' => 'Retont Business — Beheer projecten en team op één plek',

            'nav.home'     => 'Home',
            'nav.features' => 'Functies',
            'nav.pricing'  => 'Prijzen',
            'nav.faq'      => 'FAQ',
            'nav.contact'  => 'Contact',
            'nav.login'    => 'Inloggen',
            'nav.cta'      => 'Begin nu',

            'hero.title' => '<span class="accent">Retont Business</span> —<br/>Beheer projecten en team op één plek',
            'hero.sub'   => 'Beheer projecten, taken, klanten en facturen vanuit één dashboard. Volg voortgang, log uren en stuur accurate facturen — zonder de chaos van losse tools.',
            'hero.cta1'  => 'Start 30 dagen gratis',
            'hero.cta2'  => 'Bekijk de demo',

            'ds.dashboard'    => 'Dashboard',
            'ds.manage'       => 'Werk',
            'ds.projects'     => 'Projecten',
            'ds.tasks'        => 'Taken',
            'ds.clients'      => 'Klanten',
            'ds.invoices'     => 'Facturen',
            'ds.payments'     => 'Betalingen',
            'ds.general'      => 'Algemeen',
            'ds.staff'        => 'Team',
            'ds.attendance'   => 'Aanwezigheid',
            'ds.reports'      => 'Rapporten',
            'ds.settings'     => 'Instellingen',
            'ds.tabToday'     => 'Taken vandaag',
            'ds.tabRes'       => 'Actieve projecten',
            'ds.tabInv'       => 'Tijdregistraties',
            'ds.search'       => '🔍 Snel zoeken…',
            'ds.totalOrders'  => 'Actieve projecten',
            'ds.avgInv'       => 'Voltooide taken',
            'ds.weeklySales'  => 'Weekomzet',
            'ds.sales'        => '€ 10.420',
            'ds.delta1'       => '▲ 3 nieuwe projecten deze week',
            'ds.delta2'       => '▲ 12% t.o.v. vorige maand',
            'ds.todayOrders'  => 'Taken vandaag',
            'ds.paid'         => 'Voltooid',
            'ds.preparing'    => 'In uitvoering',
            'ds.order103'     => 'Sawahel Bedrijfswebsite',
            'ds.order102'     => 'Vervoer App‑project',
            'ds.order101'     => 'Basma Webshop',
            'ds.order100'     => 'Intern Devteam',
            'ds.order099'     => 'Al‑Ofuq Handelsmij.',

            'sec.controlTitle'  => 'Beheer <span class="accent">jouw bedrijf</span>',
            'sec.controlLead'   => 'Drie kernmodules in één platform voor de dagelijkse bedrijfsvoering — Projecten, Taken en Klanten.',
            'sec.allInOneTitle' => 'Alles wat je nodig hebt <span class="accent">op één plek</span>',
            'sec.allInOneLead'  => 'Een compleet platform voor elk onderdeel van je bedrijf — van projecten tot mensen tot prestatierapporten.',
            'sec.testTitle'     => 'Wat onze <span class="accent">klanten zeggen</span>',
            'sec.testLead'      => 'Duizenden teams en bedrijven vertrouwen op Retont Business voor hun dagelijkse activiteiten.',
            'sec.pricingTitle'  => 'Eenvoudige, <span class="accent">transparante prijzen</span>',
            'sec.pricingLead'   => 'Kies het plan dat bij jouw team past. Geen verborgen kosten — opzegbaar wanneer je wilt.',
            'sec.faqTitle'      => 'Veel gestelde <span class="accent">vragen</span>',
            'sec.faqLead'       => 'Antwoorden op de meest gestelde vragen over het Retont Business platform.',
            'sec.contactTitle'  => 'Neem <span class="accent">contact op</span>',
            'sec.contactLead'   => 'Ons team staat klaar om je vragen te beantwoorden en een demo op maat voor te bereiden.',

            'mock.customer1' => 'Al‑Ofuq Handelsmij.',
            'mock.date1'     => 'Factuur #INV‑2026‑047 · 15 mei 2026',
            'mock.paid'      => 'Betaald',
            'mock.item'      => 'Omschrijving',
            'mock.qty'       => 'Uren',
            'mock.price'     => 'Tarief/u',
            'mock.sum'       => 'Totaal',
            'mock.burger'    => 'UI/UX‑ontwerp',
            'mock.juice'     => 'Frontend‑ontwikkeling',
            'mock.salad'     => 'Projectmanagement',
            'mock.n1'        => '24',
            'mock.n2'        => '32',
            'mock.total'     => 'Totaal (incl. btw)',
            'mock.totalVal'  => '€ 2.965',
            'mock.order047'  => 'Project #047',
            'mock.cust2'     => 'Nasaem Tech BV',
            'mock.new'       => 'In uitvoering',
            'mock.amount'    => '€ 1.815',
            'mock.payOk'     => 'Nieuwe betaling ontvangen',

            'sp.orders.h'  => 'Van taak naar factuur, moeiteloos',
            'sp.orders.p'  => 'Zet gelogde uren in één klik om naar accurate facturen. Volg betalingen, stuur automatische herinneringen en houd voor elke klant en project een volledig financieel spoor bij.',
            'sp.orders.l1' => 'Professionele facturen in meerdere valuta met btw‑conformiteit',
            'sp.orders.l2' => 'Automatische betalingsherinneringen via e‑mail en WhatsApp',
            'sp.orders.l3' => 'Directe integratie met Stripe, PayPal en lokale gateways',

            'sp.res.h'  => 'Visueel taakbord voor projectbeheer',
            'sp.res.p'  => 'Organiseer het werk van je team visueel: van concept tot klaar. Sleep, verdeel verantwoordelijkheden en spot knelpunten vóórdat projecten uitlopen.',
            'sp.res.l1' => 'Kanban‑, Gantt‑ en lijstweergave op dezelfde data',
            'sp.res.l2' => 'Taken toewijzen met deadlines en prioriteiten',
            'sp.res.l3' => 'Tijdregistratie per taak en medewerker',

            'sp.menu.h'  => 'Ingebouwde CRM voor klantrelaties',
            'sp.menu.p'  => 'Beheer contacten, volg salesopportunities van offerte tot deal en log elke interactie op de klantpagina. Zet gesprekken om in projecten en offertes in contracten — in één klik.',
            'sp.menu.l1' => 'Aanpasbare sales pipeline',
            'sp.menu.l2' => 'Volledige offerte‑ en contracthistorie per klant',
            'sp.menu.l3' => 'Veilig klantenportaal voor projecten en facturen',

            'res.title'     => 'Projectoverzicht',
            'res.from'      => 'Periode',
            'res.to'        => 'Project',
            'res.dateA'     => '15 – 22 mei',
            'res.dateB'     => 'Sawahel Website',
            'res.t4'        => 'Homepage‑ontwerp',
            'res.fam'       => 'Sarah Al‑Mutairi · Hoge prio',
            'res.confirmed' => 'Klaar',
            'res.t7'        => 'Frontend bouwen',
            'res.phone'     => 'Deadline 20 mei · 12 uur',
            'res.pending'   => 'In uitvoering',
            'res.t2'        => 'Database‑opzet',
            'res.cust3'     => 'Faisal Al‑Nemer · Middelhoge prio',
            'res.arrived'   => 'In review',
            'res.t9'        => 'QA‑testen',
            'res.cust4'     => 'Noura Al‑Zahrani · 4 subtaken',

            'menu.tab1'   => 'Actieve klanten',
            'menu.tab2'   => 'Leads',
            'menu.tab3'   => 'Gearchiveerd',
            'menu.update' => 'Klant toevoegen',
            'menu.i1n'    => 'Al‑Ofuq Handelsmij.',
            'menu.i1d'    => '3 actieve projecten · laatst gesproken 2 dagen geleden',
            'menu.p42'    => '€ 10.200',
            'menu.i2n'    => 'Nasaem Tech BV',
            'menu.i2d'    => '2 actieve projecten · factuur open',
            'menu.p38'    => '€ 9.360',
            'menu.i3n'    => 'Basma Webshop',
            'menu.i3d'    => '1 project · in testfase',
            'menu.p28'    => '€ 6.860',
            'menu.i4n'    => 'Riyadh Destination Group',
            'menu.i4d'    => '4 projecten · VIP‑klant sinds 2023',
            'menu.p45'    => '€ 11.160',

            'ft.pos.h'   => 'Projectmanagement',
            'ft.pos.p'   => 'Plan, voer uit en monitor projecten met Kanban‑, Gantt‑ en lijstweergave.',
            'ft.rep.h'   => 'Slimme rapporten',
            'ft.rep.p'   => 'Live, directe rapporten over omzet, productiviteit en winstgevendheid per project.',
            'ft.inv.h'   => 'Facturen & offertes',
            'ft.inv.p'   => 'E‑offertes, e‑facturen en contracten, volledig fiscaal conform.',
            'ft.stock.h' => 'Tijdregistratie',
            'ft.stock.p' => 'Log uren per taak; kosten en winstgevendheid worden automatisch berekend.',
            'ft.staff.h' => 'Team & rechten',
            'ft.staff.p' => 'Beheer team, verlof, aanwezigheid en rolgebaseerde rechten.',
            'ft.comm.h'  => 'Teamchat',
            'ft.comm.p'  => 'Projectkanalen, directe meldingen en opmerkingen op taken.',
            'ft.pay.h'   => 'Online betalingen',
            'ft.pay.p'   => 'Accepteer kaarten, Apple Pay, STC Pay, Stripe, PayPal en overboekingen.',
            'ft.sup.h'   => 'Support‑tickets',
            'ft.sup.p'   => 'Ingebouwde helpdesk om klantverzoeken snel op te pakken.',

            'q1.body' => '"We gebruikten vijf verschillende tools voor projecten en facturatie. Vandaag draait alles in Retont Business — we besparen ruim 20% admintijd per maand."',
            'q1.name' => 'Khaled Al‑Omari',
            'q1.role' => 'CEO · Ithraa Digital Agency',
            'q2.body' => '"Het koppelen van uren aan taken en facturen veranderde onze werkwijze. We kennen nu de winstgevendheid van elk project — exact en in real time."',
            'q2.name' => 'Reem Al‑Dosari',
            'q2.role' => 'Operations Manager · Namat Studio',
            'q3.body' => '"Het klantenportaal geeft onze onderneming een écht professionele uitstraling. Klanten loggen in, volgen de voortgang en betalen eenvoudig."',
            'q3.name' => 'Majed Al‑Shehri',
            'q3.role' => 'Mede‑oprichter · Softwarebedrijf',

            'pr.monthly'              => 'Maandelijks',
            'pr.yearly'               => 'Jaarlijks · 20% korting',
            'pr.basic'                => 'Basis',
            'pr.pro'                  => 'Professional',
            'pr.per'                  => 'EUR/maand',
            'pr.basicNote'            => 'Voor kleine teams tot 5 gebruikers',
            'pr.proNote'              => 'Voor groeiende bedrijven met onbeperkte gebruikers',
            'pr.start'                => 'Start je proefperiode',
            'pr.popular'              => 'Populairst',
            'pr.price.basic.monthly'  => '49',
            'pr.price.basic.yearly'   => '39',
            'pr.price.pro.monthly'    => '129',
            'pr.price.pro.yearly'     => '103',

            'pt.features'   => 'Functies',
            'pt.branches'   => 'Projecten',
            'pt.one'        => 'Tot 10 projecten',
            'pt.unlim'      => 'Onbeperkt',
            'pt.staffN'     => 'Gebruikers',
            'pt.upto5'      => 'Tot 5',
            'pt.posR'       => 'Projecten & taken',
            'pt.ordRes'     => 'Facturen & offertes',
            'pt.invR'       => 'CRM & klantenportaal',
            'pt.advRep'     => 'Geavanceerde rapporten',
            'pt.deliv'      => 'Online betaalintegraties',
            'pt.supp'       => 'Support',
            'pt.email'      => 'E‑mail',
            'pt.support247' => 'Toegewijd 24/7',

            'faq.q1' => 'Kan ik het platform eerst uitproberen?',
            'faq.a1' => 'Ja, 30 dagen gratis toegang tot alle functies — geen creditcard nodig.',
            'faq.q2' => 'Is het platform cloud‑based of self‑hosted?',
            'faq.a2' => 'Volledig cloud‑based (SaaS) — geen installatie of onderhoud. Werkt in elke browser, op elk apparaat.',
            'faq.q3' => 'Ondersteunen jullie e‑facturatie?',
            'faq.a3' => 'Ja, we voldoen volledig aan de Saudische ZATCA e‑facturatie (Fatoora) regels.',
            'faq.q4' => 'Kan ik mijn data migreren?',
            'faq.a4' => 'Zeker. Ons team migreert klanten, projecten en facturen gratis vanaf elk eerder systeem.',
            'faq.q5' => 'Welke betaalmethoden kunnen mijn klanten gebruiken?',
            'faq.a5' => 'Creditcards, mada, STC Pay, Apple Pay, Stripe, PayPal en directe bankoverschrijving.',
            'faq.q6' => 'Kan ik op elk moment opzeggen?',
            'faq.a6' => 'Ja — het abonnement is maandelijks en altijd opzegbaar, zonder extra kosten.',

            'ct.loc'      => 'Locatie',
            'ct.locV'     => 'Riyad, Koninkrijk Saoedi‑Arabië',
            'ct.locL'     => 'King Fahd Road, Al‑Olaya',
            'ct.email'    => 'E‑mail',
            'ct.emailL'   => 'Voor algemene vragen en sales',
            'ct.phone'    => 'Telefoon',
            'ct.phoneL'   => 'Zondag – donderdag · 9:00 – 18:00',
            'ct.book'     => 'Plan een demo',
            'ct.imgTitle' => 'We helpen je graag',
            'ct.imgSub'   => 'Neem op elk moment contact op — het Retont Business team staat voor je klaar.',

            'footer.rights' => '© 2026 Retont Business. Alle rechten voorbehouden.',
        ];
    }

    private function de(): array
    {
        return [
            'title' => 'Retont Business — Projekte und Team an einem Ort',

            'nav.home'     => 'Start',
            'nav.features' => 'Funktionen',
            'nav.pricing'  => 'Preise',
            'nav.faq'      => 'FAQ',
            'nav.contact'  => 'Kontakt',
            'nav.login'    => 'Anmelden',
            'nav.cta'      => 'Jetzt starten',

            'hero.title' => '<span class="accent">Retont Business</span> —<br/>Projekte und Team an einem Ort',
            'hero.sub'   => 'Projekte, Aufgaben, Kunden und Rechnungen in einem Dashboard. Verfolge Fortschritt, erfasse Teamzeiten und erstelle genaue Rechnungen — ohne das Chaos verteilter Tools.',
            'hero.cta1'  => '30 Tage kostenlos testen',
            'hero.cta2'  => 'Demo ansehen',

            'ds.dashboard'    => 'Dashboard',
            'ds.manage'       => 'Arbeit',
            'ds.projects'     => 'Projekte',
            'ds.tasks'        => 'Aufgaben',
            'ds.clients'      => 'Kunden',
            'ds.invoices'     => 'Rechnungen',
            'ds.payments'     => 'Zahlungen',
            'ds.general'      => 'Allgemein',
            'ds.staff'        => 'Team',
            'ds.attendance'   => 'Anwesenheit',
            'ds.reports'      => 'Berichte',
            'ds.settings'     => 'Einstellungen',
            'ds.tabToday'     => 'Heutige Aufgaben',
            'ds.tabRes'       => 'Aktive Projekte',
            'ds.tabInv'       => 'Zeiterfassung',
            'ds.search'       => '🔍 Schnellsuche…',
            'ds.totalOrders'  => 'Aktive Projekte',
            'ds.avgInv'       => 'Erledigte Aufgaben',
            'ds.weeklySales'  => 'Wochenumsatz',
            'ds.sales'        => '10.420 €',
            'ds.delta1'       => '▲ 3 neue Projekte diese Woche',
            'ds.delta2'       => '▲ 12 % vs. Vormonat',
            'ds.todayOrders'  => 'Heutige Aufgaben',
            'ds.paid'         => 'Erledigt',
            'ds.preparing'    => 'In Bearbeitung',
            'ds.order103'     => 'Sawahel Firmenwebsite',
            'ds.order102'     => 'Transport‑App Projekt',
            'ds.order101'     => 'Basma Online‑Shop',
            'ds.order100'     => 'Internes Dev‑Team',
            'ds.order099'     => 'Al‑Ofuq Handels GmbH',

            'sec.controlTitle'  => 'Behalte <span class="accent">dein Geschäft</span> im Griff',
            'sec.controlLead'   => 'Drei Kernmodule in einer Plattform für den Arbeitsalltag — Projekte, Aufgaben und Kunden.',
            'sec.allInOneTitle' => 'Alles, was du brauchst <span class="accent">an einem Ort</span>',
            'sec.allInOneLead'  => 'Eine umfassende Plattform für jeden Bereich — von Projekten über Mitarbeiter bis zu Performance‑Reports.',
            'sec.testTitle'     => 'Was unsere <span class="accent">Kunden sagen</span>',
            'sec.testLead'      => 'Tausende Teams und Unternehmen vertrauen Retont Business im Tagesgeschäft.',
            'sec.pricingTitle'  => 'Klare, <span class="accent">transparente Preise</span>',
            'sec.pricingLead'   => 'Wähle den passenden Plan. Keine versteckten Gebühren — jederzeit kündbar.',
            'sec.faqTitle'      => 'Häufig gestellte <span class="accent">Fragen</span>',
            'sec.faqLead'       => 'Antworten auf die häufigsten Fragen zur Retont Business Plattform.',
            'sec.contactTitle'  => 'Kontaktiere <span class="accent">uns</span>',
            'sec.contactLead'   => 'Unser Team beantwortet gerne deine Fragen und bereitet eine individuelle Demo vor.',

            'mock.customer1' => 'Al‑Ofuq Handels GmbH',
            'mock.date1'     => 'Rechnung #INV‑2026‑047 · 15. Mai 2026',
            'mock.paid'      => 'Bezahlt',
            'mock.item'      => 'Position',
            'mock.qty'       => 'Std.',
            'mock.price'     => 'Satz/Std',
            'mock.sum'       => 'Summe',
            'mock.burger'    => 'UI/UX‑Design',
            'mock.juice'     => 'Frontend‑Entwicklung',
            'mock.salad'     => 'Projektmanagement',
            'mock.n1'        => '24',
            'mock.n2'        => '32',
            'mock.total'     => 'Gesamt (inkl. USt.)',
            'mock.totalVal'  => '2.965 €',
            'mock.order047'  => 'Projekt #047',
            'mock.cust2'     => 'Nasaem Tech GmbH',
            'mock.new'       => 'In Bearbeitung',
            'mock.amount'    => '1.815 €',
            'mock.payOk'     => 'Neue Zahlung erhalten',

            'sp.orders.h'  => 'Von der Aufgabe zur Rechnung — mühelos',
            'sp.orders.p'  => 'Wandle erfasste Stunden mit einem Klick in präzise Rechnungen. Verfolge Zahlungen, sende automatische Erinnerungen und führe für jeden Kunden und jedes Projekt eine vollständige Finanzhistorie.',
            'sp.orders.l1' => 'Professionelle Rechnungen in mehreren Währungen, steuerkonform',
            'sp.orders.l2' => 'Automatische Zahlungserinnerungen per E‑Mail und WhatsApp',
            'sp.orders.l3' => 'Direkte Integration mit Stripe, PayPal und lokalen Gateways',

            'sp.res.h'  => 'Visuelles Board für Aufgabenverwaltung',
            'sp.res.p'  => 'Organisiere die Arbeit deines Teams visuell — vom Entwurf bis zur Erledigung. Drag & Drop, klare Verantwortlichkeiten, Engpässe früh erkennen.',
            'sp.res.l1' => 'Kanban‑, Gantt‑ und Listenansicht auf denselben Daten',
            'sp.res.l2' => 'Aufgaben mit Fristen und Prioritäten zuweisen',
            'sp.res.l3' => 'Zeiterfassung pro Aufgabe und Teammitglied',

            'sp.menu.h'  => 'Integriertes CRM für Kundenbeziehungen',
            'sp.menu.p'  => 'Verwalte Kontakte, verfolge Verkaufschancen vom Angebot bis zum Abschluss und protokolliere jede Interaktion. Wandle Gespräche in Projekte und Angebote in Verträge — mit einem Klick.',
            'sp.menu.l1' => 'Anpassbare Sales Pipeline',
            'sp.menu.l2' => 'Vollständige Angebots‑ und Vertragshistorie pro Kunde',
            'sp.menu.l3' => 'Sicheres Kundenportal für Projekte und Rechnungen',

            'res.title'     => 'Projektboard',
            'res.from'      => 'Zeitraum',
            'res.to'        => 'Projekt',
            'res.dateA'     => '15. – 22. Mai',
            'res.dateB'     => 'Sawahel Website',
            'res.t4'        => 'Homepage‑Design',
            'res.fam'       => 'Sarah Al‑Mutairi · Hohe Prio',
            'res.confirmed' => 'Erledigt',
            'res.t7'        => 'Frontend‑Umsetzung',
            'res.phone'     => 'Fällig 20. Mai · 12 Stunden',
            'res.pending'   => 'In Bearbeitung',
            'res.t2'        => 'Datenbank‑Setup',
            'res.cust3'     => 'Faisal Al‑Nemer · Mittlere Prio',
            'res.arrived'   => 'In Prüfung',
            'res.t9'        => 'QA‑Tests',
            'res.cust4'     => 'Noura Al‑Zahrani · 4 Unteraufgaben',

            'menu.tab1'   => 'Aktive Kunden',
            'menu.tab2'   => 'Leads',
            'menu.tab3'   => 'Archiviert',
            'menu.update' => 'Kunde anlegen',
            'menu.i1n'    => 'Al‑Ofuq Handels GmbH',
            'menu.i1d'    => '3 aktive Projekte · letzter Kontakt vor 2 Tagen',
            'menu.p42'    => '10.200 €',
            'menu.i2n'    => 'Nasaem Tech GmbH',
            'menu.i2d'    => '2 aktive Projekte · Rechnung offen',
            'menu.p38'    => '9.360 €',
            'menu.i3n'    => 'Basma Online‑Shop',
            'menu.i3d'    => '1 Projekt · in der Testphase',
            'menu.p28'    => '6.860 €',
            'menu.i4n'    => 'Riyadh Destination Group',
            'menu.i4d'    => '4 Projekte · VIP‑Kunde seit 2023',
            'menu.p45'    => '11.160 €',

            'ft.pos.h'   => 'Projektmanagement',
            'ft.pos.p'   => 'Plane, führe aus und überwache Projekte mit Kanban‑, Gantt‑ und Listenansicht.',
            'ft.rep.h'   => 'Intelligente Berichte',
            'ft.rep.p'   => 'Live‑Berichte zu Umsatz, Produktivität und Profitabilität pro Projekt.',
            'ft.inv.h'   => 'Rechnungen & Angebote',
            'ft.inv.p'   => 'E‑Angebote, E‑Rechnungen und Verträge — voll steuerkonform.',
            'ft.stock.h' => 'Zeiterfassung',
            'ft.stock.p' => 'Erfasse Stunden pro Aufgabe; Kosten und Profitabilität werden automatisch berechnet.',
            'ft.staff.h' => 'Team & Rechte',
            'ft.staff.p' => 'Team, Urlaub, Anwesenheit und rollenbasierte Rechte verwalten.',
            'ft.comm.h'  => 'Team‑Chat',
            'ft.comm.p'  => 'Projektkanäle, sofortige Hinweise und Kommentare zu Aufgaben.',
            'ft.pay.h'   => 'Online‑Zahlungen',
            'ft.pay.p'   => 'Karten, Apple Pay, STC Pay, Stripe, PayPal und Überweisungen akzeptieren.',
            'ft.sup.h'   => 'Support‑Tickets',
            'ft.sup.p'   => 'Integriertes Helpdesk, um Kundenanfragen schnell zu beantworten.',

            'q1.body' => '"Wir nutzten fünf verschiedene Tools für Projekte und Abrechnung. Heute läuft alles in Retont Business — wir sparen über 20 % der monatlichen Verwaltungszeit."',
            'q1.name' => 'Khaled Al‑Omari',
            'q1.role' => 'CEO · Ithraa Digital Agency',
            'q2.body' => '"Die Verknüpfung von Zeiten, Aufgaben und Rechnungen hat unsere Arbeitsweise verändert. Wir kennen die Profitabilität jedes Projekts exakt und in Echtzeit."',
            'q2.name' => 'Reem Al‑Dosari',
            'q2.role' => 'Operations Manager · Namat Studio',
            'q3.body' => '"Das Kundenportal gibt unserem Unternehmen einen wirklich professionellen Auftritt. Kunden loggen sich ein, verfolgen den Fortschritt und zahlen mühelos."',
            'q3.name' => 'Majed Al‑Shehri',
            'q3.role' => 'Mitgründer · Softwareunternehmen',

            'pr.monthly'              => 'Monatlich',
            'pr.yearly'               => 'Jährlich · 20 % sparen',
            'pr.basic'                => 'Basis',
            'pr.pro'                  => 'Professional',
            'pr.per'                  => 'EUR/Monat',
            'pr.basicNote'            => 'Für kleine Teams bis zu 5 Nutzer',
            'pr.proNote'              => 'Für wachsende Unternehmen mit unbegrenzten Nutzern',
            'pr.start'                => 'Testen starten',
            'pr.popular'              => 'Am beliebtesten',
            'pr.price.basic.monthly'  => '49',
            'pr.price.basic.yearly'   => '39',
            'pr.price.pro.monthly'    => '129',
            'pr.price.pro.yearly'     => '103',

            'pt.features'   => 'Funktionen',
            'pt.branches'   => 'Projekte',
            'pt.one'        => 'Bis zu 10 Projekte',
            'pt.unlim'      => 'Unbegrenzt',
            'pt.staffN'     => 'Nutzer',
            'pt.upto5'      => 'Bis zu 5',
            'pt.posR'       => 'Projekte & Aufgaben',
            'pt.ordRes'     => 'Rechnungen & Angebote',
            'pt.invR'       => 'CRM & Kundenportal',
            'pt.advRep'     => 'Erweiterte Berichte',
            'pt.deliv'      => 'Online‑Zahlungs‑Integrationen',
            'pt.supp'       => 'Support',
            'pt.email'      => 'E‑Mail',
            'pt.support247' => 'Dediziert 24/7',

            'faq.q1' => 'Kann ich vorher testen?',
            'faq.a1' => 'Ja — 30 Tage kostenlos mit allen Funktionen, ohne Kreditkarte.',
            'faq.q2' => 'Cloud oder Self‑Hosting?',
            'faq.a2' => 'Vollständig cloudbasiert (SaaS) — keine Installation, keine Wartung. Läuft in jedem Browser auf jedem Gerät.',
            'faq.q3' => 'Unterstützt ihr E‑Rechnungen?',
            'faq.a3' => 'Ja, wir sind vollständig konform mit dem saudischen ZATCA E‑Invoicing (Fatoora).',
            'faq.q4' => 'Kann ich Daten migrieren?',
            'faq.a4' => 'Absolut. Unser Team migriert Kunden, Projekte und Rechnungen kostenlos von jedem bisherigen System.',
            'faq.q5' => 'Welche Zahlungsmethoden können meine Kunden nutzen?',
            'faq.a5' => 'Kreditkarten, mada, STC Pay, Apple Pay, Stripe, PayPal und SEPA‑Überweisung.',
            'faq.q6' => 'Kann ich jederzeit kündigen?',
            'faq.a6' => 'Ja — das Abo ist monatlich und jederzeit ohne Zusatzkosten kündbar.',

            'ct.loc'      => 'Standort',
            'ct.locV'     => 'Riad, Königreich Saudi‑Arabien',
            'ct.locL'     => 'King Fahd Road, Al‑Olaya',
            'ct.email'    => 'E‑Mail',
            'ct.emailL'   => 'Für allgemeine Anfragen und Vertrieb',
            'ct.phone'    => 'Telefon',
            'ct.phoneL'   => 'Sonntag – Donnerstag · 9 – 18 Uhr',
            'ct.book'     => 'Demo buchen',
            'ct.imgTitle' => 'Wir sind für dich da',
            'ct.imgSub'   => 'Melde dich jederzeit — das Retont Business Team ist für dich bereit.',

            'footer.rights' => '© 2026 Retont Business. Alle Rechte vorbehalten.',
        ];
    }
}
